/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icoffee;

/**
 *
 * @author Phuc Anh
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chuyenTrangThanhToan = new javax.swing.JButton();
        labelTong = new javax.swing.JLabel();
        Tong = new javax.swing.JLabel();
        Mon1 = new javax.swing.JButton();
        Mon2 = new javax.swing.JButton();
        Mon3 = new javax.swing.JButton();
        Mon4 = new javax.swing.JButton();
        Mon5 = new javax.swing.JButton();
        Mon6 = new javax.swing.JButton();
        Gia1 = new javax.swing.JLabel();
        Gia3 = new javax.swing.JLabel();
        Gia2 = new javax.swing.JLabel();
        Gia5 = new javax.swing.JLabel();
        Gia4 = new javax.swing.JLabel();
        Gia6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSMon = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chuyenTrangThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chuyenTrangThanhToan.setText("Thanh toan");
        chuyenTrangThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chuyenTrangThanhToanMouseClicked(evt);
            }
        });

        labelTong.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelTong.setText("Total");

        Tong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tong.setText("60.000d");
        Tong.setToolTipText("");

        Mon1.setText("Ca phe");
        Mon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon1MouseClicked(evt);
            }
        });

        Mon2.setText("Ca phe sua");
        Mon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon2MouseClicked(evt);
            }
        });

        Mon3.setText("Bac xiu");
        Mon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon3MouseClicked(evt);
            }
        });

        Mon4.setText("Tra da");
        Mon4.setPreferredSize(new java.awt.Dimension(74, 22));
        Mon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon4MouseClicked(evt);
            }
        });

        Mon5.setText("Nuoc suoi");
        Mon5.setMaximumSize(new java.awt.Dimension(74, 22));
        Mon5.setMinimumSize(new java.awt.Dimension(74, 22));
        Mon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon5MouseClicked(evt);
            }
        });

        Mon6.setText("Tra dao");
        Mon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon6MouseClicked(evt);
            }
        });

        Gia1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia1.setText("20.000d");

        Gia3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia3.setText("20.000d");

        Gia2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia2.setText("20.000d");

        Gia5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia5.setText("20.000d");

        Gia4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia4.setText("20.000d");

        Gia6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gia6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gia6.setText("20.000d");

        DSMon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DSMon.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        DSMon.setToolTipText("");
        DSMon.setAlignmentX(3.0F);
        DSMon.setAlignmentY(3.0F);
        DSMon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(DSMon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chuyenTrangThanhToan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Mon1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(Gia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Mon2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Mon3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Gia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Gia3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Gia4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mon4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Gia5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(Mon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Mon6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(Gia6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Tong))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Gia1, Mon1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Mon1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Gia1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Mon2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(Mon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Gia3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gia2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Mon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Mon6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Mon5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gia5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gia6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gia4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tong)
                            .addComponent(labelTong))
                        .addGap(27, 27, 27)
                        .addComponent(chuyenTrangThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Mon1, Mon4, Mon5});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Mon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon1MouseClicked

    private void Mon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon2MouseClicked

    private void Mon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon3MouseClicked

    private void Mon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon4MouseClicked

    private void Mon5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon5MouseClicked

    private void Mon6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Mon6MouseClicked

    private void chuyenTrangThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chuyenTrangThanhToanMouseClicked
        // TODO add your handling code here:
        
        ThanhToan thanhtoan = new ThanhToan();
        thanhtoan.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_chuyenTrangThanhToanMouseClicked

    
    private void addItem(String name, int price) {
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> DSMon;
    private javax.swing.JLabel Gia1;
    private javax.swing.JLabel Gia2;
    private javax.swing.JLabel Gia3;
    private javax.swing.JLabel Gia4;
    private javax.swing.JLabel Gia5;
    private javax.swing.JLabel Gia6;
    private javax.swing.JButton Mon1;
    private javax.swing.JButton Mon2;
    private javax.swing.JButton Mon3;
    private javax.swing.JButton Mon4;
    private javax.swing.JButton Mon5;
    private javax.swing.JButton Mon6;
    private javax.swing.JLabel Tong;
    private javax.swing.JButton chuyenTrangThanhToan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTong;
    // End of variables declaration//GEN-END:variables
}
