/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icoffee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 *
 * @author Phuc Anh
 */
public class QuanLyMENU extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyMENU
     */
    public QuanLyMENU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThemMonMoi = new javax.swing.JFrame();
        AddButton = new javax.swing.JButton();
        tenMonField = new javax.swing.JTextField();
        giaMonField = new javax.swing.JTextField();
        tenMon = new javax.swing.JLabel();
        giaMon = new javax.swing.JLabel();
        labelThemMon = new javax.swing.JLabel();
        Huy = new javax.swing.JButton();
        ChonMon = new javax.swing.JComboBox<>();
        Open = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        giaMoi = new javax.swing.JTextField();
        GiaCu = new javax.swing.JLabel();
        Gia = new javax.swing.JLabel();
        GiaMoi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        Tep = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        tuyChinh = new javax.swing.JMenu();
        themMonButton = new javax.swing.JMenuItem();
        xoaMon = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        AddButton.setText("Them");

        tenMonField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        giaMonField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tenMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenMon.setText("Ten Mon");

        giaMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaMon.setText("Gia Mon");

        labelThemMon.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelThemMon.setText("Them Mon");

        Huy.setText("Huy");

        javax.swing.GroupLayout ThemMonMoiLayout = new javax.swing.GroupLayout(ThemMonMoi.getContentPane());
        ThemMonMoi.getContentPane().setLayout(ThemMonMoiLayout);
        ThemMonMoiLayout.setHorizontalGroup(
            ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemMonMoiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelThemMon)
                .addGap(103, 103, 103))
            .addGroup(ThemMonMoiLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ThemMonMoiLayout.createSequentialGroup()
                        .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(giaMon)
                            .addComponent(tenMon))
                        .addGap(43, 43, 43)
                        .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(giaMonField)
                            .addComponent(tenMonField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                    .addGroup(ThemMonMoiLayout.createSequentialGroup()
                        .addComponent(Huy)
                        .addGap(49, 49, 49)
                        .addComponent(AddButton)
                        .addGap(44, 44, 44)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        ThemMonMoiLayout.setVerticalGroup(
            ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThemMonMoiLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelThemMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenMonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenMon))
                .addGap(18, 18, 18)
                .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaMon)
                    .addComponent(giaMonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(ThemMonMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(Huy))
                .addGap(34, 34, 34))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1, 1));

        ChonMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca Phe", "Ca Phe Sua", "Tra Da", "Lipton" }));

        Open.setText("Mo");

        Save.setText("Luu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Ca Phe");

        giaMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        GiaCu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GiaCu.setText("Gia");

        Gia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Gia.setText("20.000d");

        GiaMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        GiaMoi.setText("Gia Moi");

        Tep.setText("Tep");

        jMenuItem2.setText("Save");
        Tep.add(jMenuItem2);

        jMenuBar1.add(Tep);

        tuyChinh.setText("Tuy Chinh");

        themMonButton.setText("Them Mon");
        themMonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMonButtonActionPerformed(evt);
            }
        });
        tuyChinh.add(themMonButton);

        xoaMon.setText("Xoa Mon");
        tuyChinh.add(xoaMon);

        jMenuBar1.add(tuyChinh);

        jMenu4.setText("Help");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChonMon, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GiaCu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Gia))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Save, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GiaMoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(giaMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChonMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Open))
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GiaCu)
                    .addComponent(Gia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GiaMoi)
                    .addComponent(giaMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(Save)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void themMonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMonButtonActionPerformed
        // TODO add your handling code here:
        ThemMonMoi.setSize(400, 317);
        centreWindow(ThemMonMoi);
        ThemMonMoi.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_themMonButtonActionPerformed

    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMENU().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> ChonMon;
    private javax.swing.JLabel Gia;
    private javax.swing.JLabel GiaCu;
    private javax.swing.JLabel GiaMoi;
    private javax.swing.JButton Huy;
    private javax.swing.JButton Open;
    private javax.swing.JButton Save;
    private javax.swing.JMenu Tep;
    private javax.swing.JFrame ThemMonMoi;
    private javax.swing.JTextField giaMoi;
    private javax.swing.JLabel giaMon;
    private javax.swing.JTextField giaMonField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelThemMon;
    private javax.swing.JLabel tenMon;
    private javax.swing.JTextField tenMonField;
    private javax.swing.JMenuItem themMonButton;
    private javax.swing.JMenu tuyChinh;
    private javax.swing.JMenuItem xoaMon;
    // End of variables declaration//GEN-END:variables
}
